name: Build Gradle project

on:
  push:

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v2
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Setup rgClone
      run: |
        chmod +x ./gradle/gradlew
        cd ./gradle
        ./gradlew setupRgCloneCli -PrgCloneEndpoint="${{ secrets.RGCLONE_ENDPOINT }}" -PrgCloneToken="${{ secrets.RGCLONE_TOKEN }}"
    - name: Create Data-Container (lifetime 5m)
      run: |
        CONTAINERNAME="test_${{ github.run_id }}_${{ github.run_attempt }}"
        echo "Container Name: ${CONTAINERNAME}"
        cd ./gradle
        ./gradlew createDataContainer -PrgCloneEndpoint="${{ secrets.RGCLONE_ENDPOINT }}" -PcontainerName="${CONTAINERNAME}"
    - name: View all rgClone images and containers
      run: |
        cd ./gradle
        ./gradlew getAll -PrgCloneEndpoint="${{ secrets.RGCLONE_ENDPOINT }}"